language: java
jdk:
- openjdk8
services:
- docker
env:
  global:
  - secure: BMKAXAt9ECkPpm6deZJraI/c0oiftoK7pFSfxvRWyaOWoTvX2TM/Mj4w7CB5nmlWF2SinxuvpwFJ2kk5CW2N5ynJeTNGWV+kmVHV27tnz1z65VIp2ISvdiR7/Jx6HQ4x4BA8la6pV3D3/i+cs2p+kJhXgXB3Jj5sho/uW3DBPh6Up9YQS7URcjQM7WFCUk+8DblrD2qLB+PyT5+NAWZT+6RjPCe/weRgk95wiX5fIvwl1/qTS91a4JmNRATNRXBnayvqozIex38bNe65N591GVdplaKHZiMfYyl4bEV5YL30UyCAwKeHb6djUW63G0dSFBQvPLw8cwkfDsCjoEchvw0KS1bE2B2r5pyq+UzyVGwRz4pAJ4oFZtwb7n/qgBq1k5iLD0w0/fdmz7f+TdWNhXq7+ppFu+ymHtWWpgTpb0iRqkYwLgVY/Ry0+K03QfMA/AeLx6ny8QAtVqFuNPYgeoU8VUeeO/cxjk59t+ktwvunMf4CCmDeHtrIJPpJ3RFBJBHiZqrvviL+edJpeScDNYXQpNo3eKCfIn9NiHp4wYV7rPiEvgtL47W582bRkskWrK6Cvl0bTUA+6C9T8S5kF7Pp2xuQVk56dVjopCls3oAn9eoDgNWo3jLNKR9WHu3zRnsN0q7eT/TaShocQVNDvzanLRQFj6FTjSUocjSqrDk=
  - secure: PiHaYDg3GhHmpGAPIP1K28DqGXyqD8HwkT/NttqHbWXmzFwK0CfY3okKiiS/MQs0oaKXvAHz+Qu+Xnqim8+6hlb8iKBdFg5Ca8Q9vPutA3v2jzAA1wj61ZTsRnpIDZKYl03KfRPHer69OHYbb6EBHA1oza9FGTAhvMVZRivFr296rgojrmVEU1xhGteqFQCl1EMp/Vqw537M/8FoU9tRqO+y4C7mmsphox22ERR4Lw1ZHZFA1WIVxAya30UTVbaBFYA3cvoMN2nsXJ96/SCA15CEMavt47Me3YY+CT6twty7ikgflxVGDHQgmBdip0r1PhRu0PeFhINH8KZSaayURgiaV130WEHO0fcky0aZ+Q9okEkUeoW/VoZENAV4I4/iKUAcbI393YXl3Yx8hWXhsLktd/ykwI9DDQYFF0CsLEI1PmHnGZTUrq5tvkxHHfZFj8Xh1bK2xr4X8/o9F6Fjl1b1WPzy28RgzPfSc1stioru9VPslCJRTcSmeMq2loQCep/fO9bOnMu8SURgoU6zEWm1l3/WkEg91vkcUIdarL6Xs2GKmgDUN6T+vusftInbBFbd2l6dcMzN9xG95GQeaUofDigeNqdgLGWwN4gmjlELhDvu3lIMSqW+ah29Rs1Wr1XwRSYGzp7eT/dQXjfyi3zLsE+k2j3YI4oet16KoVs=
  - secure: N42REuE60Lkdjum8SH4K1SM+sdgax9TeeO6d3VipJ2cX1vDNIliwG/Fvb1Y6u/CXM+Y8LfZ10+RhoUoVnNPROjAsnAXYP7jGW6XdABRwtm9oE5RPxdAKLctFKB9q14mAPgRvC4X6O3epQ9MWo/hQT7R+ITGWTyazvRzLEf0D0hse+hk2tsFvdG7Go0xcgw5dvwQvG1BVxRWo7A5SI63GbGM7FbOhfFuBgz8N0RnykE+UkqOlj0NtErECTYAJO/+V7Vhxy3YPsNwGW9F6qRsmy8v/LuZYcPNcpWcxUmVIp16lNTpdiezyaRNpr9Js6fj2Hfo5Q4ysLed/9BERFxjqyk69nXMwDsBd/dNnUvleMvLM5Ku9hEcQAX1Qh8BCYk/ju0bnweqbIShpmTTuf5Z88yMqcSPqX+AKiLyRSpY8/QSsbSJryfYfXMoFC5k+CRDzlezybsl4aeQxG0aRWZgefxm5+g/EFQuCiu7f05GkB31eN3IIYkSX8YYDFwKkx761Ii9AbTnlqvGd1qNInmeuyb/Ti8esAh1l2YV2kUQN907Bw89kbCzyUW8CQDvyyDw4M7lb+ap8torzEUhojUlyLDUE38nzteJGwEFr7PiZFU7neTlbBuTyHZkXwwcVNCUGmxD2nhHVZ9CIa8yQ6ASbRI18G0R+iMavysox9Pne4BU=
  - secure: BSb+vawKrbFJgXB8Il+r2WQvZt6T3l4XA1Q9gcZTQj4HKVzqCy2fbLj+sG0rd+jdefQxQGMbPWePzuJwEmu/4YkDdB8msLs7z4XvPz/0B6Oe2KjdT/Ui7TFe876A1BWVTHZLlgJFDu7pGOD7AZrt357qZPxplmcZOLHCsH2XOp3di/RHHd/iwb5wRY/xIEpJFObxdkvP1SILJnyoeU/KQ0HhmNPGtomAXErXeN9Jn1X1IA+ethUQJQJNX+YJFSaMK4wzxghfifLOqCxCvyDPPxBEtEgGodARDOHABhSabf8x8A2k4TVn0Oa34jgsOZ8koKryYxKht2+LU2zLXZ9eF/QJAkWiknGgLexsY53UXthetoF+r4A6cFmvJ1TS3HMUWFcokHiXD58O7EcFXhE95skIKDO+JNqfW7hvrrcfYU9A87bhXacG/m/lPF8KtDVSKNu72nahmD4l3CQKU3XnfPGQ41rnVoyHLB15IfvFgaRI4FJfjRlIplaUdKtTDcCIF0yv+IH776Jm1ip2Dn/zlRBBlmPLobLt4AU+HlkVLFvIzfTez65kq2HiHnAXusFF9KPsIUUGrDE8TBFOZ8REIPeL3FU8HfskCfrd6+A+erf+CVlierC9AGnp5yk5KIfEBVXHNUKeRHcYTloVFgb7DZljpAb6oiaysUoDjX52LkI=
  - COMMIT=${TRAVIS_COMMIT::7}

before_install:
- docker pull openjdk:8-jdk-alpine
script:
- mvn test
- mvn clean package
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: demodockerwebapp
